# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/invoice_parser',
                'doc_host': 'https://HamzaFarhan.github.io',
                'git_url': 'https://github.com/HamzaFarhan/invoice_parser',
                'lib_path': 'invoice_parser'},
  'syms': { 'invoice_parser.core': {},
            'invoice_parser.imports': {},
            'invoice_parser.utils': { 'invoice_parser.utils.empty_part': ('utils.html#empty_part', 'invoice_parser/utils.py'),
                                      'invoice_parser.utils.empty_row': ('utils.html#empty_row', 'invoice_parser/utils.py'),
                                      'invoice_parser.utils.first_empty_row': ('utils.html#first_empty_row', 'invoice_parser/utils.py'),
                                      'invoice_parser.utils.full_row': ('utils.html#full_row', 'invoice_parser/utils.py')}}}
