# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['empty_part', 'empty_row', 'full_row', 'first_empty_row', 'load_csv', 'load_invoice_model']

# %% ../nbs/00_utils.ipynb 2
from .imports import *

# %% ../nbs/00_utils.ipynb 4
def empty_part(x):
    return x == "" or x == None


def empty_row(x):
    return all([empty_part(i) for i in x])


def full_row(x):
    return all([not empty_part(i) for i in x])


def first_empty_row(table):
    for i, row in enumerate(table):
        if empty_row(row):
            return i
    return -1


def load_csv(path):
    loader = CSVLoader(file_path=path)
    return loader.load()

def load_invoice_model(device='cuda:0'):
    return SetFitModel.from_pretrained("HamzaFarhan/InvoiceOrNot", device=default_device(device))
